Introduce sorting by FFT filtered blur detection.
deepfakes/faceswap pull request #1147
Opened 2021-04-18 20:28 UTC by pfakanator

Blur detection using the mean value of the magnitude spectrum of and inverted FFT.

2021-04-18 20:28 UTC, pep8speaks commented
Hello @pfakanator! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`tools/sort/sort.py`](https://github.com/deepfakes/faceswap/blob/f4d9ba2489da59229077f61944bd125c6b02ee17/tools/sort/sort.py):

> [Line 173:100](https://github.com/deepfakes/faceswap/blob/f4d9ba2489da59229077f61944bd125c6b02ee17/tools/sort/sort.py#L173): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 99 characters)

2021-04-18 21:07 UTC, torzdf requested changes

2021-04-18 21:07 UTC, torzdf commented on tools/sort/cli.py
> +            choices=("blur", "fft-blur", "face", "face-cnn", "face-cnn-dissim", "face-yaw", "hist",
Please change to "blur-fft"

2021-04-18 21:07 UTC, torzdf commented on tools/sort/sort.py
> +                                                           leave=False)]
To fix the Flake8 line too long nag:
```py
                     for filename, image, metadata in tqdm(
                         self._loader.load(),
                         desc="Estimating fft filtered blur score",
                         total=self._loader.count,
                         leave=False)]
```

2021-04-18 21:21 UTC, pfakanator reviewed
fixed blur-fft and pep8

2021-04-18 21:56 UTC, pfakanator reviewed
PEP8!

2021-04-19 03:50 UTC, pfakanator reviewed
fixed flake8 errors

2021-04-19 09:47 UTC, torzdf approved these changes

2021-04-19 09:48 UTC, merged